name: "be-events-photoshare"

services:
  photoshare-nginx:
    build:
      context: ./../
      dockerfile: docker/nginx/Dockerfile
      args:
        ENVIRONMENT: docker-sql
    container_name: photoshare-nginx
    environment:
      COUNTRY_CODE: ro
      ENVIRONMENT: dev
    volumes:
      - type: bind
        source: ./../public
        target: /var/www/youremember/public
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.photoshare.entrypoints=web'
      - "traefik.http.routers.photoshare.rule=Host(`photoshare.localhost`)"
      - 'traefik.docker-sql.network=proxy'
      - 'traefik.http.services.photoshare.loadbalancer.server.port=80'
    depends_on:
      - photoshare-php

  photoshare-php:
    build:
      context: ./../
      dockerfile: docker/php-fpm/Dockerfile
      args:
        ENVIRONMENT: docker-sql
    container_name: photoshare-phpfpm
    volumes:
      - "~/.gitconfig:/etc/gitconfig"
      - "~/.aws/credentials:/root/.aws/credentials"
      - type: bind
        source: ./../
        target: /var/www/youremember
    environment:
      ENVIRONMENT: docker-sql
      COUNTRY_CODE: ro
      APP_ENV: dev
    networks:
      - proxy

networks:
  proxy:
    external: true
