services:
  rmb-nginx:
    build:
      context: ./../
      dockerfile: docker/nginx/Dockerfile
      args:
        ENVIRONMENT: docker-sql
    container_name: rmb-nginx
    environment:
      COUNTRY_CODE: ro
      ENVIRONMENT: dev
    volumes:
      - type: bind
        source: ./../public
        target: /var/www/youremember/public
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rmb.entrypoints=web'
      - "traefik.http.routers.rmb.rule=Host(`rmb.localhost`) || Host(`a2fab3c1996d.ngrok-free.app`)"
      - 'traefik.docker-sql.network=proxy'
      - 'traefik.http.services.rmb.loadbalancer.server.port=80'
    depends_on:
      - rmb-php

  rmb-php:
    build:
      context: ./../
      dockerfile: docker/php-fpm/Dockerfile
      args:
        ENVIRONMENT: docker-sql
    container_name: rmb_phpfpm
    volumes:
      - "~/.gitconfig:/etc/gitconfig"
      - "~/.aws/credentials:/root/.aws/credentials"
      - type: bind
        source: ./../
        target: /var/www/youremember
    environment:
      ENVIRONMENT: docker-sql
      COUNTRY_CODE: ro
      APP_ENV: dev
    networks:
      - proxy

networks:
  proxy:
    external: true
