worker_processes 2;
worker_priority 0;

events {
  worker_connections 4096;
  use epoll;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # Nginx will handle gzip compression of responses from the app server
  gzip on;
  gzip_proxied any;
  gzip_types text/plain application/json;
  gzip_min_length 1000;

  log_format apm '"$time_local" client=$remote_addr '
                 'method=$request_method request="$request" '
                 'request_length=$request_length '
                 'status=$status bytes_sent=$bytes_sent '
                 'body_bytes_sent=$body_bytes_sent '
                 'referer=$http_referer '
                 'user_agent="$http_user_agent" '
                 'upstream_addr=$upstream_addr '
                 'upstream_status=$upstream_status '
                 'request_time=$request_time '
                 'upstream_response_time=$upstream_response_time '
                 'upstream_connect_time=$upstream_connect_time '
                 'kyc_id="$upstream_http_x_kyc_id" '
                 'upstream_header_time=$upstream_header_time';

  server {
    listen 80;
    root /var/www/youremember/public;
    server_name  _  AnotherServerNameForPhpStorm;
    client_max_body_size 10M;

    location / {
      add_header 'Access-Control-Allow-Origin' '*' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
      add_header 'Access-Control-Allow-Headers' '*';

      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,X-Id-Token,X-Tokens,X-Auth-Token';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
      }

      # try to serve file directly, fallback to index.php
      try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
      add_header 'Access-Control-Allow-Origin' '*' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
      add_header 'Access-Control-Allow-Headers' '*';

      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,X-Id-Token,X-Tokens,X-Auth-Token';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
      }

      fastcgi_pass photoshare-phpfpm:9000;
      fastcgi_split_path_info ^(.+\.php)(/.*)$;
      include fastcgi_params;
      fastcgi_param environment prod;
      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
      fastcgi_param DOCUMENT_ROOT $realpath_root;
      internal;
    }

    location /nginx-check {
      access_log off;
      return 200;
    }

    location /nginx_status {
      stub_status on;
      allow 127.0.0.0/8;
      deny all;
    }

    location ~ ^/(status|ping)$ {
      allow 127.0.0.0/8;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
      fastcgi_pass photoshare-phpfpm:9000;
      deny all;
    }

    error_log /var/log/nginx/youremember-error.log;
    access_log /proc/self/fd/2 apm;
  }
}
