max_input_vars=6000
xdebug.log=/tmp/xdebug.log
xdebug.mode=debug,coverage
xdebug.start_with_request=yes
xdebug.idekey=youremember
;add below your machine's IP (the VPN one) otherwise discover_client_host must be set true
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.discover_client_host=true
memory_limit=2048M
